### ISSUE TITLE
cannot install on ubuntu 16.04

### ISSUE THREAD

**Issue by despiegk** [zielmicha/capnp.nim#4]
![image](https://cloud.githubusercontent.com/assets/6021844/20392573/b7a3dd7c-acd8-11e6-8192-72cb00cc5b92.png)

**Comment by despiegk** [comment]
doesnt work in osx either

![image](https://cloud.githubusercontent.com/assets/6021844/21286150/5980be0a-c44c-11e6-9266-9235671e046d.png)

**Comment by zielmicha** [comment]
Interesting. It seems that Nimble ignores nim.cfg when building from remote repository, but not when run locally.

**Comment by zielmicha** [comment]
Should be fixed in 0.0.3.
