### ISSUE TITLE
unpackPointer failed with "expected struct, found 3:

### ISSUE THREAD

**Issue by iwanbk** [zielmicha/capnp.nim#6]
Hello,
i tried to decoded a binary string using `unpackPointer` and got this error
```
unpack.nim(314)          unpackPointer
unpack.nim(281)          unpackStruct
unpack.nim(255)          parseStruct
Error: unhandled exception: expected struct, found 3 [CapnpFormatError]
```
i can decode it fine using Go library.

Because type `3` seems to be wanted by `unpackCap`, i tried to use `unpackCap` directly but got this error
```
/root/.nimble/pkgs/capnp-0.0.3/capnp/unpack.nim(292, 12) Error: undeclared identifier: 'createFromCap'
```

**Comment by zielmicha** [comment]
Does this message contain capabilities? If so, it probably only makes sense to use RPC layer to unserialize it. If you just want to ignore them, use something like that

```
 let unpacker = newUnpackerFlat(data)
unpacker.getCap = proc(id: int): CapServer = return nothingImplemented
unpacker.unpackPointer(0, T)
```

This library works in a slightly different way than Go and C++ ones - it deserializes everything at once - so it needs to know types of everything beforehand (except `AnyPointer`s).

**Comment by zielmicha** [comment]
Mm, looking at the stack trace it seems that the message only contains a capability. Capability is just a number (which makes sense only as part of RPC stream). Could you give more details about the message (preferably copy it here in hex form).

**Comment by iwanbk** [comment]
@zielmicha 
thanks for looking at this issue.

The data was not serialized using rpc layer.
I actually expected it to be a struct.

This is the first 20 bytes
```
03 00 00 00 30 02 00 00 01 02 00 00 03 06 00 00 05 0A 00 00 00
```

In case it helps, this is the .capnp file
```
struct TlogBlock {
    sequence @0: UInt32;
    size @1 :UInt32;
    crc  @2 :Text;
    data @3 :Data;
}

struct TlogAggregation {
    name @0 :Text;
    size @1: UInt64;
    timestamp @2 :UInt64;
    blocks @3 :List(TlogBlock);
}
```

**Comment by zielmicha** [comment]
It looks like multisegment message (this is default format used by C++ library). Make sure you create unpacker using `newUnpacker` (not `newUnpackerFlat`).

(note: there is still one feature missing to fully support multisegment messages, so certain messages may raise "not implemented" error)

**Comment by iwanbk** [comment]
thanks, it works fine now.

sorry for this `noise`, i thought i've tried newUnpacker.
Yes, the message is indeed generated by C++
