### ISSUE TITLE
Error: undeclared identifier: 'getInterfaceId'

### ISSUE THREAD

**Issue by traverseda** [zielmicha/capnp.nim#7]
I'm presuming this is just because interface-inheretence is not yet implemented by capnp.nim, but as this is a learning project, it would be nice to be sure before I put the project on hold. It might also just be that I'm instantiating the service incorrectly, as the documentation is sparse.

You can see what code I have now here: https://github.com/traverseda/NayukiFilesystem

**Comment by zielmicha** [comment]
> interface-inheretence is not yet implemented by capnp.nim

You are correct, but it simply ignores any parent interfaces. You should be able to use them with `castAs`. It also doesn't support generics, but if you are willing to sacrifice type safety, `castAs` will also suffice.

If you can paste the error message, I might assist you in resolving it (
I'm using this library a lot in [metac](https://github.com/metacontainer/metac), so apart for missing generics and inheritance there shouldn't be any other problems)

**Comment by traverseda** [comment]
```
Hint: tags_schema [Processing]
/home/traverseda/.nimble/pkgs/reactor-0.5.0/reactor/async/asyncmacro.nim(268, 14) Hint: 'asyncDefer' is declared but not used [XDeclaredButNotUsed]
nayukiFsService.nim(9, 13) template/generic instantiation from here
nayukiFsService.nim(16, 12) template/generic instantiation from here
nayukiFsService.nim(18, 64) template/generic instantiation from here
/home/traverseda/.nimble/pkgs/capnp-0.0.3/caprpc/common.nim(62, 39) template/generic instantiation from here
/home/traverseda/.nimble/pkgs/collections-0.5.0/collections/iface.nim(225, 32) template/generic instantiation from here
/home/traverseda/.nimble/pkgs/collections-0.5.0/collections/iface.nim(249, 52) template/generic instantiation from here
/home/traverseda/.nimble/pkgs/collections-0.5.0/collections/iface.nim(159, 39) template/generic instantiation from here
/home/traverseda/.nimble/pkgs/capnp-0.0.3/caprpc/common.nim(56, 6) Error: undeclared identifier: 'getInterfaceId'
```

So I'm pretty sure I'm initializing the RPC server incorrectly. I based it off the `examples/calculator_server.nim`, since it looked like it supported multiple connections and `examples/simplerpc.nim` looked like it only supported one connection and/or was meant to be a client.

I'll try reading though some metac code to get a better idea of how to start an rpc server, but I'd definitly appreciate any insight you can offer.

**Comment by zielmicha** [comment]
Here is you module fixed:
```
import reactor, capnp, caprpc
# you can't use `from xxx import yyy` for schema files
import capnpSchema.NayukiFilesystem_schema, capnpSchema.files_schema, capnpSchema.tags_schema

let serviceVersion = Version(kind:VersionKind.semVar,major:0, minor:0, patch:0)

type ServiceImpl = ref object of RootObj

proc version(self: ServiceImpl): Future[Version] {.async.} =
  return serviceVersion

# implement other methods here

capServerImpl(ServiceImpl, [Services])

proc main() {.async.} =
  # let sys = newTwoPartyClient(await connectTcp("127.0.0.1:7890")) # localhost:6789
  let server = await createTcpServer(7890)

  let services = ServiceImpl()

  echo "waiting for incoming connections"
  asyncFor conn in server.incomingConnections:
    echo "connection received"
    discard newTwoPartyServer(conn.BytePipe, services.asServices.toCapServer)

when isMainModule:
  main().runMain()
```
